<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit18a81a838bde72a6ce7edd20e3ab047d
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WPAllImport\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit18a81a838bde72a6ce7edd20e3ab047d', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WPAllImport\Composer\Autoload\ClassLoader();
        spl_autoload_unregister(array('ComposerAutoloaderInit18a81a838bde72a6ce7edd20e3ab047d', 'loadClassLoader'));

        $map = require __DIR__ . '/autoload_namespaces.php';
        foreach ($map as $namespace => $path) {
            $loader->set($namespace, $path);
        }

        $map = require __DIR__ . '/autoload_psr4.php';        
        foreach ($map as $namespace => $path) {                        
            $loader->setPsr4($namespace, $path);
        }        

        $classMap = require __DIR__ . '/autoload_classmap.php';
        if ($classMap) {
            $loader->addClassMap($classMap);
        }

        $loader->register(true);

        return $loader;
    }
}
