<?php

class ShortcodesTest extends WP_UnitTestCase {
  protected $related_links_shortcode = '
    [related-links include_siblings=false]
    <a href="http://google.com">Google</a>
     <a href="http://bing.com">Bing</a>
    [/related-links]
  ';

  function test_shortcode_container_exists() {
    $this->assertTrue( shortcode_exists( 'container' ) );
  }

  function test_shortcode_container_creates_containers() {
    $container = do_shortcode( '[container][/container]' );

    $this->assertContains( '<div class="container', $container );
    $this->assertNotContains( 'pad-bot-md', $container );
    $this->assertNotContains( 'pad-top-sm', $container );
    $this->assertContains( '</div>', $container );
  }

  function test_shortcode_container_has_specific_margins() {
    $container = do_shortcode( '[container margin=xl][/container]' );

    $this->assertContains( '<div class="container', $container );
    $this->assertContains( 'space-top-xl', $container );
    $this->assertContains( 'space-bot-xl', $container );
    $this->assertContains( '</div>', $container );
  }

  function test_shortcode_container_creates_gray_containers() {
    $container = do_shortcode( '[container type=gray][/container]' );

    $this->assertContains( '<div class="gray-back', $container );
    $this->assertContains( '<div class="container', $container );
    $this->assertNotContains( 'pad-bot-md', $container );
    $this->assertNotContains( 'pad-top-md', $container );
    $this->assertContains( '</div>', $container );
  }

  function test_shortcode_sidebar_exists() {
    $this->assertTrue( shortcode_exists( 'sidebar' ) );
  }

  function test_shortcode_column_exists() {
    $this->assertTrue( shortcode_exists( 'column' ) );
  }

  function test_shortcode_panel_exists() {
    $this->assertTrue( shortcode_exists( 'panel' ) );
  }

  function test_shortcode_button_exists() {
    $this->assertTrue( shortcode_exists( 'button' ) );
  }

  function test_shortcode_asu_breadcrumbs_exists() {
    $this->assertTrue( shortcode_exists( 'asu_breadcrumbs' ) );
  }

  function test_shortcode_page_feature_exists() {
    $this->assertTrue( shortcode_exists( 'page_feature' ) );
  }

  function test_shortcode_related_links_exists() {
    $this->assertTrue( shortcode_exists( 'related-links' ) );
  }

  function test_shortcode_related_links_returns_string() {
    $content = do_shortcode( $this->related_links_shortcode );

    $this->assertContains( 'related-articles', $content, 'The related-articles css class should be generated by the shortcode' );
    $this->assertContains( '<a href="http://google.com">Google</a>', $content );
    $this->assertContains( '<a href="http://bing.com">Bing</a>', $content );
  }
}